services:
  - type: web
    name: memoraai-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
    routes:
      - type: rewrite
        source: /api/*
        destination: https://memoraai-ans7.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
