services:
  - type: web
    name: memoraai-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
